### ISSUE TITLE
Perform additional checks in Travis CI.

### ISSUE THREAD

**Issue by shurcooL** [google/go-cmp#13]
@dsnet, in https://github.com/google/go-cmp/pull/9#discussion_r127847401, I asked if you wanted a PR that adds a `gofmt` check to Travis CI, and you said "that would be great". So I sent #12 for that.

However, I'd like to propose performing additional checks in CI. After years of iterating on it, I've arrived at the following `.travis.yml` script, which I [generate](https://github.com/shurcooL/cmd/blob/3775d1a67e78fba6a8380e30337340465a0b30e3/gorepogen/template.go#L50-L66) for all my Go repositories:

```yml
sudo: false
language: go
go:
  - 1.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
```

Here's an explanation of its features over the minimal `.travis.yml` change I sent in #12 that adds the `gofmt` only:

- Use `-s` flag with `gofmt` to ensure code simplifications are made.
- Use `-race` flag with `go test` to enable race detector.
- Run `go vet` on the directory to catch `vet` issues.
- Run a fast-finish allowed failure build on Go tip version. Allowed failure means a temporary issue in Go tip won't fail the build, but one can still manually see if there are some real failures in that version by manually checking Travis builds occasionally. Fast-finish just means the overall build status is computed faster, without waiting for allowed failure steps (I'm not really sure why it's an option instead of just being a default). See more info about it at https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/.
- Move `go get -t -v ./...` step from `install` step to `script`. This one is very minor and more of a personal preference, but it makes it so that if there's a build failure in any of the dependencies, the build appears as a red "failure", rather than a gray "error".

@dsnet Let me know if you'd like any or all of the above enhancements, I'm happy to send a followup PR.
